### ISSUE TITLE
unofficial grunt plugins shouldn't be in the grunt-contrib-* namespace

### ISSUE THREAD

**Issue by jasonkarns** [jasonlam604/grunt-rename-util#1]
It might be a good idea to rename this plugin. The grunt-contrib namespace is generally reserved for official plugins.

http://gruntjs.com/creating-plugins#naming-your-task

**Comment by maxkorp** [comment]
Thirding this. I quite like the plugin, but I can't support a misleading behavior like that (even if you most didn't intend for it to be, which it doesn't seem like you did). Please fix.

**Comment by adamclerk** [comment]
Fourthing this. Though it was an official plugin...but it's not.

**Comment by jasonlam604** [comment]
Sorry guys, no problem... will rename and republish
