### ISSUE TITLE
Incompatible w/ Grunt 1.0.0

### ISSUE THREAD

**Issue by roytruelove** [jasonlam604/grunt-rename-util#4]
See /http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies

**Comment by farzd** [comment]
please update peerDependency of your package to "grunt": ">=0.4.0"

**Comment by jasonlam604** [comment]
Fixed, package is renamed to grunt-rename-util due misleading naming with the official plugins...
